### ISSUE TITLE
FileSystem Plugin Browser Compatibility

### ISSUE THREAD

**Issue by NDMO** [bezlio/bezlio-plugins#8]
The FileSystemPlugin is currently using a Base64 string to transmit files over ServiceBus.  Javascript code can 
transform this into a file on desktop platforms but it appears to not work on iOS.  Diagnose where this is coming unhinged and develop a fix.

**Comment by aellis** [comment]
This was just an issue with the way the Bezl was written.  Recent testing on iOS has shown this to not be an issue.
