### ISSUE TITLE
GetArgs support for enumerables

### ISSUE THREAD

**Issue by NDMO** [bezlio/bezlio-plugins#9]
Right now GetArgs just allows us to return placeholder text - enhance this to allow plugins to potentially return back an enumeration of values to be presented on the connection screen as a drop-down as opposed to a text box.  For example, the 'context' drop-down for the SQL Server plugin would say 'Workflow', 'Epicor', etc.

**Comment by aellis** [comment]
As a small clarification on this one, I would expect this to be purely be a code change on portal for now.  So right now the placeholder text might say something like 'Location name where .SQL files are stored' and we just show that as the placeholder text.  What I would like to to is allow for plugins to continue to put text like this in there and it will work exactly the same, but if the text in that field was formatted something like this:

[Option1,Option2,Option3]

(or whatever format you come up with that is easiest to implement) that we would render this as a combo box having those values instead.

**Comment by ahodakovskaya** [comment]
Issue was ported over to bezlio repository.
